name: Aggiorna Feed Kaufland Polonia
on:
  schedule:
    - cron: '30 */6 * * *'  # Ogni 6 ore (offset di 30 min)
  workflow_dispatch:

jobs:
  update-feed-pl:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica codice
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Installa dipendenze
        run: pip install -r requirements.txt
      
      - name: Esegui sincronizzazione BigBuy Polonia
        env:
          BIGBUY_API_KEY: ${{ secrets.BIGBUY_API_KEY }}
          COUNTRY_CODE: PL
        run: python bigbuy_kaufland.py
      
      - name: Commit feed Polonia
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add kaufland_feed_pl.csv index.html feed_info_pl.json
          
          if git diff --cached --quiet; then
            echo "Nessuna modifica per la Polonia"
          else
            git commit -m "Aggiorna feed Polonia $(date '+%Y-%m-%d %H:%M:%S')"
            git push
            echo "Feed Polonia aggiornato con successo!"
          fi
