name: Aggiorna Feed Kaufland Poland
on:
  schedule:
    - cron: '5 */6 * * *'  # Ogni 6 ore (offset di 5 min)
  workflow_dispatch: 

jobs:
  update-feed-pl:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica codice
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Wait for other workflows to complete
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Installa dipendenze
        run: pip install -r requirements.txt
      
      - name: Esegui sincronizzazione BigBuy Poland
        env:
          BIGBUY_API_KEY: ${{ secrets.BIGBUY_API_KEY }}
          COUNTRY_CODE: PL
        run: python bigbuy_kaufland.py
      
      - name: Check generated files
        run: |
          echo "=== Files generated ==="
          ls -la *.csv *.html *.json 2>/dev/null || echo "No files found"
          echo "=== Poland-specific files ==="
          find . -name "*_pl.*" -o -name "kaufland_feed_pl.csv" 2>/dev/null || echo "No PL files found"
          echo "=== File sizes ==="
          if [ -f "kaufland_feed_pl.csv" ]; then
            wc -l kaufland_feed_pl.csv
            echo "First few lines of CSV:"
            head -3 kaufland_feed_pl.csv
          fi
          if [ -f "feed_info_pl.json" ]; then
            echo "JSON info content:"
            cat feed_info_pl.json
          fi
      
      - name: Commit feed Poland con retry
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Clean up any unstaged changes first
          git stash --include-untracked || true
          
          # Pull latest changes
          git pull origin main || git pull origin master || true
          
          # Apply stash if it exists
          git stash pop || true
          
          # Add Poland-specific files only if they exist
          files_to_add=""
          
          if [ -f "kaufland_feed_pl.csv" ]; then
            lines=$(wc -l < kaufland_feed_pl.csv)
            if [ "$lines" -gt 1 ]; then
              files_to_add="$files_to_add kaufland_feed_pl.csv"
              echo "✅ Found kaufland_feed_pl.csv with $lines lines"
            else
              echo "❌ kaufland_feed_pl.csv exists but is empty"
              exit 1
            fi
          else
            echo "❌ Missing kaufland_feed_pl.csv"
            exit 1
          fi
          
          if [ -f "index_pl.html" ]; then
            files_to_add="$files_to_add index_pl.html"
            echo "✅ Found index_pl.html"
          else
            echo "❌ Missing index_pl.html"
          fi
          
          if [ -f "feed_info_pl.json" ]; then
            files_to_add="$files_to_add feed_info_pl.json"
            echo "✅ Found feed_info_pl.json"
          else
            echo "❌ Missing feed_info_pl.json"
          fi
          
          if [ -n "$files_to_add" ]; then
            git add $files_to_add
            
            if git diff --cached --quiet; then
              echo "Nessuna modifica per la Poland"
            else
              # Get data fingerprint for commit message
              fingerprint=""
              if [ -f "feed_info_pl.json" ]; then
                fingerprint=$(grep -o '"random_seed": [0-9]*' feed_info_pl.json | grep -o '[0-9]*')
              fi
              
              # Create commit message with stats
              product_count=""
              if [ -f "feed_info_pl.json" ]; then
                product_count=$(grep -o
