name: Aggiorna Feed Kaufland Italia
on:
  schedule:
    - cron: '0 */6 * * *'  # Ogni 6 ore
  workflow_dispatch:  # Pulsante manuale

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica codice
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Installa dipendenze
        run: pip install -r requirements.txt
      
      - name: Esegui sincronizzazione BigBuy
        env:
          BIGBUY_API_KEY: ${{ secrets.BIGBUY_API_KEY }}
        run: python bigbuy_kaufland.py
      
      - name: Verifica file creati
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Looking for CSV files:"
          find . -name "*.csv" -type f
      
      - name: Commit feed aggiornato
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all generated files
          git add kaufland_feed.csv index.html feed_info.json
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update feed $(date '+%Y-%m-%d %H:%M:%S')"
            git push
            echo "Feed updated successfully!"
          fi
